name: Update Dependency Graph for Gradle
on:
  push:
    branches:
      - main
      - Gradle-dependency-graph-3e5af558d893dccd
  workflow_dispatch: 
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Set up Java
        id: setup
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Submit dependencies
        id: submit
        uses: gradle/actions/dependency-submission@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
      - name: Log snapshot for user validation
        id: validate
        run: cat
          /home/runner/work/toolargetool/toolargetool/dependency-graph-reports/update_dependency_graph_for_gradle-dependency-graph.json
          | jq
    permissions:
      contents: write
