name: Update Dependency Graph for Gradle
on:
  push:
    branches:
      - main
  workflow_dispatch: 
jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        id: checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v4.2.1
      - name: Set up Java
        id: setup
        uses: actions/setup-java@a7ab372554b6eb1a8eb25e7d9aec1cc9f3ea1a76 # v4.2.1
        with:
          distribution: temurin
          java-version: 17
      - name: Submit dependencies
        id: submit
        uses: gradle/actions/dependency-submission@cd4b95f1dffd155d6d8f6b8c195a3ff2f9f77a5d # v4.1.0
      - name: Log snapshot for user validation
        id: validate
        run: cat
          /home/runner/work/toolargetool/toolargetool/dependency-graph-reports/update_dependency_graph_for_gradle-dependency-graph.json
          | jq
    permissions:
      contents: write
