name: Publish release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish with gradlew
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.PGP_PRIVATE_KEY_PASSWORD }}
        run: ./gradlew -PuseInMemoryPgpKeys :toolargetool:publishToSonatype closeAndReleaseSonatypeStagingRepository