name: Publish release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Publish with gradlew
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingKeyPassword: ${{ secrets.PGP_PRIVATE_KEY_PASSWORD }}
        run: ./gradlew -PuseInMemoryPgpKeys :toolargetool:publishReleasePublicationToSonatypeRepository